### ISSUE TITLE
Add licence?

### ISSUE THREAD

**Issue by yochannah** [rseng/remote-bingo#8]
Hey @vsoch ! I'd recently been thinking about a similar bingo style game for a conference and was really pleased to discover you'd made this! 

I would love to fork this for potential use at [BCC 2020](https://bcc2020.github.io/) - any chance you'd be able to add a licence to the repo? I'm also happy to make a PR myself, but a licence is a big enough thing I don't want to try to guess which licence a person might prefer :)

**Comment by vsoch** [comment]
Yes of course! Will do in a few minutes!

**Comment by vsoch** [comment]
Ok all set! https://github.com/rseng/remote-bingo/commit/5eb5d70692690ed5b04a54e99426405023d86301. If you make improvements please contribute back to the repository, and if you fork the repository and want to add the link to the readme here that would be awesome!

**Comment by yochannah** [comment]
that was so fast - thanks! And yes, we will do! 🚀
